// Re-export shim. Implementation lives in ./migrations/.
// Existing imports of `save-migrations` continue to work via this barrel.
export {
  CURRENT_SAVE_VERSION,
  clampGeneratorFuel,
  migrateSave,
} from "./migrations";
export type {
  SaveGameV1,
  SaveGameV2,
  SaveGameV3,
  SaveGameV4,
  SaveGameV5,
  SaveGameV6,
  SaveGameV7,
  SaveGameV8,
  SaveGameV9,
  SaveGameV10,
  SaveGameV11,
  SaveGameV12,
  SaveGameV13,
  SaveGameV14,
  SaveGameV15,
  SaveGameV16,
  SaveGameV17,
  SaveGameV18,
  SaveGameV19,
  SaveGameV20,
  SaveGameV21,
  SaveGameV22,
  SaveGameV23,
  SaveGameV24,
  SaveGameV25,
  SaveGameV26,
  SaveGameV27,
  SaveGameV28,
  SaveGameV29,
  SaveGameV30,
  SaveGameV31,
  SaveGameV32,
  SaveGameLatest,
} from "./migrations";
