// Type facade for the game domain.
export type {
  GameMode,
  AssetType,
  BuildingType,
  FloorTileType,
  MachinePriority,
  PlacedAsset,
  Inventory,
  ToolKind,
  HotbarSlot,
  SmithyState,
  ManualAssemblerState,
  Direction,
  AutoMinerEntry,
  ConveyorItem,
  ConveyorState,
  AutoSmelterStatus,
  AutoSmelterProcessing,
  AutoSmelterEntry,
  AutoAssemblerRecipeId,
  AutoAssemblerStatus,
  AutoAssemblerEntry,
  UIPanel,
  BatteryState,
  GeneratorState,
  GameNotification,
  GameState,
} from "../store/types";
