import type { SceneDefinition } from "../scene-types";
import {
  asset,
  autoAssembler,
  autoMiner,
  autoSmelter,
  belt,
  conveyorCorner,
  conveyorSplitter,
  generator,
  powerNode,
  resource,
  serviceHub,
  stoneFloorRect,
  undergroundIn,
  undergroundOut,
  warehouse,
} from "../scene-builder/helpers";

export const debugSceneLayout: SceneDefinition = {
  id: "debug",
  label: "Extended debug scene",
  mode: "debug",
  resetGlobalInventory: true,
  globalInventory: { coins: 99999 },
  purchasedBuildings: ["generator"],
  placedBuildings: ["generator"],
  starterDrone: { hubId: "service-hub-proto" },
  resources: [
    resource("stone-deposit", "stone_deposit", 2, 2, { fixed: true }),
    resource("iron-deposit", "iron_deposit", 75, 2, { fixed: true }),
    resource("copper-deposit", "copper_deposit", 2, 45, { fixed: true }),
    resource("tree-debug-a", "tree", 10, 10),
    resource("tree-debug-b", "tree", 12, 14),
    resource("tree-debug-c", "tree", 21, 32),
    resource("stone-debug-a", "stone", 16, 8),
    resource("stone-debug-b", "stone", 24, 17),
    resource("iron-debug-a", "iron", 31, 9),
    resource("copper-debug-a", "copper", 8, 37),
  ],
  assets: [
    asset("map-shop", "map_shop", 39, 24, { fixed: true }),
    serviceHub("service-hub-proto", 42, 24, {
      fixed: true,
      droneIds: ["starter"],
    }),
    warehouse("warehouse-starter", 39, 22),
    warehouse("warehouse-smelter-output", 67, 0),
    generator("generator-debug-a", 68, 5, { fuel: 500, running: true }),
    generator("generator-debug-b", 71, 5, { fuel: 500, running: true }),
    powerNode("power-pole-generator", 71, 4),
    powerNode("power-pole-splitter", 69, 4),
    powerNode("power-pole-smelter-output", 68, 2),
    powerNode("power-pole-smelter-input", 72, 3),
    powerNode("power-pole-assembler", 66, 6),
    autoMiner("auto-miner-iron", 75, 2, "west", "iron-deposit"),
    belt("belt-miner-output-a", 74, 2, "west"),
    belt("belt-miner-output-b", 73, 2, "west"),
    belt("belt-smelter-input", 72, 2, "west"),
    autoSmelter("auto-smelter-iron", 70, 2, "west", "iron"),
    conveyorCorner("corner-smelter-down", 69, 2, "south"),
    conveyorCorner("corner-route-west", 69, 3, "west"),
    belt("belt-splitter-input", 68, 3, "west"),
    conveyorSplitter("splitter-debug", 67, 3, "west"),
    belt("belt-warehouse-return", 67, 2, "north"),
    undergroundIn("underground-in-debug", 67, 4, "south", "underground-out-debug"),
    undergroundOut("underground-out-debug", 67, 7, "south", "underground-in-debug"),
    autoAssembler("auto-assembler-debug", 65, 7, "west", "metal_plate"),
    belt("belt-assembler-output", 64, 7, "west"),
    warehouse("warehouse-assembler-output", 62, 7, { direction: "east" }),
  ],
  floorTiles: [
    stoneFloorRect("floor-generator-debug-a", 68, 5, 2, 2),
    stoneFloorRect("floor-generator-debug-b", 71, 5, 2, 2),
  ],
};